var c = document.getElementById("myCanvas");
              var ctx = c.getContext("2d");
              ctx.font = "10px Georgia";
              ctx.font = "30px Verdana";
var gradient = ctx.createLinearGradient(100, 0, c.width, 0);
              gradient.addColorStop("0", "magenta");
              gradient.addColorStop("0.5", "blue");
              gradient.addColorStop("1.0", "red");
              ctx.strokeStyle = gradient;
              ctx.strokeText("eager to learn", 50, 70);
              var c = document.getElementById("myCanvas");
              var ctx = c.getContext("2d");
              ctx.font = "10px Georgia";
              ctx.font = "30px Verdana";
var gradient = ctx.createLinearGradient(100, 0, c.width, 0);
              gradient.addColorStop("0", "magenta");
              gradient.addColorStop("0.5", "blue");
              gradient.addColorStop("1.0", "red");
              ctx.strokeStyle = gradient;
              ctx.strokeText("success comes", 630, 70);
var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(250, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
                var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(840, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
                var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(790, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
                var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(740, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
                var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(690, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
                var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(640, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
                
var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(200, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
var c = document.getElementById("myCanvas");
                var ctx = c.getContext("2d");
                ctx.beginPath();
                ctx.arc(150, 110, 30, 0, 2 * Math.PI);
                ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.beginPath();
                  ctx.arc(100, 110, 30, 0, 2 * Math.PI);
                  ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.beginPath();
                  ctx.arc(50, 110, 30, 0, 2 * Math.PI);
                  ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.lineWidth = 10;
                  ctx.beginPath();
                  ctx.moveTo(100, 5);
                  ctx.lineTo(10, 5);
                  ctx.lineTo(50, 50);
                  ctx.lineJoin = 'miter';
                  ctx.stroke();
                  var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.lineWidth = 10;
                  ctx.beginPath();
                  ctx.moveTo(880, 5);
                  ctx.lineTo(10, 5);
                  ctx.lineTo(50, 50);
                  ctx.lineJoin = 'miter';
                  ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.lineWidth = 10;
                  ctx.beginPath();
                  ctx.moveTo(50, 5);
                  ctx.lineTo(100, 5);
                  ctx.lineTo(50, 50);
                  ctx.lineJoin = 'miter';
                  ctx.stroke();
                //   var c = document.getElementById("myCanvas");
                //   var ctx = c.getContext("2d");
                //   ctx.lineWidth = 10;
                //   ctx.beginPath();
                //   ctx.moveTo(50, 5);
                //   ctx.lineTo(800, 5);
                //   ctx.lineTo(850, 50);
                //   ctx.lineJoin = 'miter';
                //   ctx.stroke();
                //   var c = document.getElementById("myCanvas");
                //   var ctx = c.getContext("2d");
                //   ctx.lineWidth = 10;
                //   ctx.beginPath();
                //   ctx.moveTo(50, 5);
                //   ctx.lineTo(800, 5);
                //   ctx.lineTo(850, 50);
                //   ctx.lineJoin = 'miter';
                //   ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.lineWidth = 10;
                  ctx.beginPath();
                  ctx.moveTo(290, 5);
                  ctx.lineTo(10, 5);
                  ctx.lineTo(50, 50);
                  ctx.lineJoin = 'miter';
                  ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.lineWidth = 10;
                  ctx.beginPath();
                  ctx.moveTo(50, 5);
                  ctx.lineTo(200, 5);
                  ctx.lineTo(250, 50);
                  ctx.lineJoin = 'miter';
                  ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.lineWidth = 10;
                  ctx.beginPath();
                  ctx.moveTo(50, 5);
                  ctx.lineTo(300, 5);
                  ctx.lineTo(250, 50);
                  ctx.lineJoin = 'miter';
                  ctx.stroke();
var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(50, 200, 40, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,0,127)';
                  ctx.fill();
                  var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(620, 200, 40, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(127,0,255)';
                  ctx.fill();

                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(60, 200, 20, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,182,193)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(630, 200, 20, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(153,51,255)';
                  ctx.fill();

var c = document.getElementById("myCanvas");
                  var ctx = c.getContext("2d");
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(270, 200, 40, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,0,190)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(845, 200, 40, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,0,0)';
                  ctx.fill();

                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(255, 200, 20, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,100,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(660, 200, 17, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(178,102,255)';
                  ctx.fill();

                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(230, 200, 17, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,170,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(690, 200, 17, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(204,153,255)';
                  ctx.fill();

                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(200, 200, 15, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,200,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(720, 200, 15, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,204,229)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(740, 200, 13, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,153,153)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(760, 200, 12, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,102,102)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.arc(780, 200, 11, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,51,51)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.arc(800, 200, 10, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(255,51,51)';
                  ctx.fill();

                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(173, 200, 13, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,240,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.moveTo(200,100);
                  ctx.arc(149, 200, 12, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,255,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.arc(127, 200, 11, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,255,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.arc(107, 200, 10, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,255,255)';
                  ctx.fill();
                  ctx.beginPath();
                  ctx.arc(89, 200, 9, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(0,255,255)'
                  ctx.fill();
                  ctx.beginPath();
                  ctx.arc(74, 200, 9, 0, 2 * Math.PI);
                  ctx.closePath();
                  ctx.fillStyle = 'rgb(102,255,255)';
                  ctx.fill();


const title = document.getElementById('title');
title.innerHTML = '<em>Hobby & Creation</em>';
title.style.backgroundColor = 'white';
const title2 = document.getElementById('title2');
title2.innerHTML = '<em>Femas Febriano</em>';

let data = {
    Name : "Femas Febriano",
    Department : "Informatics Engineering",
    Contact : "+6283851976201",
    Email : "febrianofemas@gmail.com",
    Religion : "Islam"  
};
console.log(data);

function dataPersonal(Name, Age, Height, Weight){
    this.Name = Name;
    this.Age = Age;
    this.Height = Height;
    this.Weight = Weight;

}
let data1 = new dataPersonal("Femas", "21", "170cm", "50kg");
console.log(data1);

function sekaliClick(){
    document.querySelector("p");
}
function duakaliClick(){
    document.querySelector("p").innerHTML="Dipanggil saat dua kali klik";
}
function tampilkanContextMenu(){
    document.querySelector("p");
}

var h1Node = document.getElementById("judul");
